### ISSUE TITLE
Undeclared dependency on Test::LongString

### ISSUE THREAD

**Issue by andk** [mattp-/Plack-Middleware-DebugLogging#1]
As per subject. Grep:

http://search.cpan.org/grep?release=Plack-Middleware-DebugLogging-0.001004;string=Test::LongString;n=1;C=0

Sample fail report:

http://www.cpantesters.org/cpan/report/43591769

HTH&&Thanks,
(Disclaimer: this was discovered by statistical analysis, I'm not speaking as a user)

**Comment by mattp-** [comment]
thanks
https://metacpan.org/release/MATTP/Plack-Middleware-DebugLogging-0.001005
